language: cpp

os:
  - osx

compiler:
  - clang
  - gcc
  - g++
  
before_install:
  - pip install cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=1 ..
  - cmake --build .
  - ctest

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications:
  email: false
