language: cpp

os:
  - osx

compiler:
  - clang
  - gcc
  - g++
  
before_install:
  - pip install cpp-coveralls
  - brew install opencv

script:
  - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .
  - ctest

notifications:
  email: false
